# Utiliser une image de base Python
FROM python:3.8-slim

# Créer un répertoire de travail
WORKDIR /app

# Copier le fichier de script Python dans le répertoire de travail
COPY server.py /app/server.py

# Rendre le fichier exécutable (même si ce n'est pas nécessaire pour Python)
RUN chmod +x /app/server.py && ls -l /app

# Exposer le port 8080
EXPOSE 8080

# Commande pour exécuter le serveur Python
CMD ["python", "/app/server.py"]
